name: Checks before merging PR

on:
  push:
    branches-ignore: [main]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm ci
          npm run lint:js
          npm run build

  success:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This command should pass for status check to pass
